trigger:
  - master

pool:
  vmImage: unbuntu-latest

steps:
  - script: echo Hello Worl!
    displayName: "Run a one line script"

  - script: |
      echo Akansha!!
      echo another line
    displayName: "run two line of script"
